myData <- read.table("household_power_consumption.txt", sep=";", header=TRUE)
myData['DateTime'] = paste(myData$Date, myData$Time)
myData$DateTime = strptime(myData$DateTime, "%d/%m/%Y %H:%M:%S")
myData$Date = strptime(myData$Date, "%d/%m/%Y")
newData = subset(myData, Date==strptime("02/02/2007", "%m/%d/%Y") | Date==strptime("02/01/2007", "%m/%d/%Y"))
png("plot3.png", width=480, height=480)
plot(newData$DateTime, as.numeric(as.character(newData$Sub_metering_1)), type="l", ylab="Energy Sub Meeting", xlab="")
points(newData$DateTime, as.numeric(as.character(newData$Sub_metering_2)), type="l", col="red")
points(newData$DateTime, as.numeric(as.character(newData$Sub_metering_3)), type="l", col="blue")
legend("topright", lty=1, col=c("black", "red", "blue"), legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
dev.off()